### ISSUE TITLE
如何得到数据集的.feat.GPT文件呢？我在您提供的数据处理代码中并没有找到这一块。

### ISSUE THREAD

**Issue by Cxx-0** [ysh-1998/LRD#3]

**Comment by ysh-1998** [comment]
使用的是gpt的文本向量api，即text-embedding-ada-002

**Comment by LQlq123** [comment]
> 使用的是gpt的文本向量api，即text-embedding-ada-002

我有相同的疑惑，那这意味着MovieLens重的.feat.GPT是和Office一样的吗，只是名字上有所区别吗

**Comment by LQlq123** [comment]
> 使用的是gpt的文本向量api，即text-embedding-ada-002
我有相同的疑惑，这是指MovieLens中的.feat.GPT和Office中的是一样的吗？是否两者只是名字上的差异？

**Comment by ysh-1998** [comment]
MovieLens和Office两个数据集使用的文本信息不一样，所以用gpt获得的文本向量也不一样

**Comment by LQlq123** [comment]
> MovieLens和Office两个数据集使用的文本信息不一样，所以用gpt获得的文本向量也不一样

感谢回复：）

**Comment by LQlq123** [comment]
> MovieLens和Office两个数据集使用的文本信息不一样，所以用gpt获得的文本向量也不一样

再次打扰，请问.feat.GPT是依据MovieLens中哪一个文件获得的呢？

**Comment by ysh-1998** [comment]
> > MovieLens和Office两个数据集使用的文本信息不一样，所以用gpt获得的文本向量也不一样
> 
> 再次打扰，请问.feat.GPT是依据MovieLens中哪一个文件获得的呢？

数据目录下的ml-100k.text文件

**Comment by LQlq123** [comment]
> > > MovieLens和Office两个数据集使用的文本信息不一样，所以用gpt获得的文本向量也不一样
> > 
> > 
> > 再次打扰，请问.feat.GPT是依据MovieLens中哪一个文件获得的呢？
> 
> 数据目录下的ml-100k.text文件

感谢：）
