### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Siqi-Jia** [ysh-1998/LRD#6]
您好，Office.feat.GPT这个文件是怎么得到的呢，可以提供其他数据集的GPT文件吗？

**Comment by ysh-1998** [comment]
您好👋感谢关注，这个文件是通过openai的文本向量API获得的，具体可以参考[link](https://platform.openai.com/docs/guides/embeddings)。其它数据集的GPT文件请查阅data目录的[README](https://github.com/ysh-1998/LRD/tree/main/data#readme)中提供的google driver链接。

**Comment by Siqi-Jia** [comment]
谢谢！
